const descriptions = [
  {
    title: "Master Thesis Project",
    "Short description": "Personalized data comic implemented as a part of my master thesis.",
    "Long description": "In my master thesis, I focused on developing different methods for personalized data storytelling. This prototype thematizes the user's personal reading dataset, discussing trends in the individual data and giving personalized recommendations.",
    "Acquired skills": ["Modern JavaScript", "git", "Node.js", "React", "d3.js", "OpenAI API"],
    name: "master-project",
    link: "master-project/dist/index.html",
    timeframe: "Summer semester 2024",
  },
  /*{
    title: "Master Thesis Proposal",
    "Short description": "Prototype of the data comic I proposed for my master thesis",
    "Long description": "Prototype of the data comic I proposed for my master thesis",
    "Acquired skills": [],
    name: "data-comic",
    link: "data-comic/dist/index.html",
    timeframe: "Summer semester 2024",
  },*/
  {
    title: "React Book Management Application",
    "Short description": "Advanced web development project with a focus on tooling and frameworks. React app created with in a group of five.",
    "Long description": "This project focused on getting to know the essentials of modern web development: Tools like Webpack, Babel and Eslint, Frameworks like React, agile development in teams and much more. Implemented in a group of five.",
    "Acquired skills": ["Modern JavaScript", "git", "Webpack", "Babel", "ESLint", "Node.js", "TDD", "vitest", "React"],
    name: "iBooks",
    link: "iBooks/dist/index.html",
    timeframe: "Winter semester 2023/24",
  },
  {
    title: "Svelte LogBook",
    "Short description": "Single page application that presents a logbook for space travelers. The entries are stored in the local storage of the browser.",
    "Long description": "The final assigment for the fictional GOTO-Mars project. This logbook application focuses on applying a component-based framework, in this case Svelte. ",
    "Acquired skills": ["Svelte", "git", "localstorage", "JavaScript", "Bootstrap"],
    name: "LogBook",
    link: "LogBook/dist/index.html",
    timeframe: "Summer semester 2023",
  },
  {
    title: "Single Page Application",
    "Short description": "Single Page Application with a focus on using d3.js and bootstrap. The server side is an API implemented with Express.js. Created with three fellow students as an assignment for a web technologies class.",
    "Long description": "As an assignment for a class on web technologies, three fellow students and I were tasked to develop a single page application for the fictional research project 'GOTO Mars Research', displaying their data about rocket missions to Mars. We implemented an API that allows the client to fetch the JSON data and use it for a counter and a visualization.",
    "Acquired skills": ["git", "d3.js", "Express.js", "JavaScript", "Bootstrap"],
    name: "SPA",
    link: "SPA/client/index.html",
    timeframe: "Summer semester 2023",
  },
  {
    title: "d3 Graph Visualization",
    "Short description": "Interactive visualization of a publications dataset. Created as an assignment for a data visualization class.",
    "Long description": "This was a graded assignment for my information visualization class. The base was a dataset about publications. The goal was to implement a node-link-diagram where the nodes represent keywords that were used in the publications, and the links are keywords that are used in the same publications. The node size encodes the number of publications using the keyword. I implemented a click interaction that lists the publications using a selected keyword. The graph layout was achieved using d3-force. Furthermore, the data was filtered so that only the nodes and links above a certain size limit are displayed.",
    "Acquired skills": ["d3.js", "Javascript"],
    name: "graph",
    link: "D3_Graph_Visualization/graph.html",
    timeframe: "Summer semester 2023",
  },
  {
    title: "d3 Scatterplot",
    "Short description": "Interactive scatterplot visualization of a movie dataset. Created as an assignment for a data visualization class.",
    "Long description": "As a graded assignment for a information visualization class, I received a dataset about movies. The task was to implement a visualization from scratch, using d3.js. The goal was to visualize the movies by the 15 directors who had directed the most movies, as well as 3 additional variables. I chose to symbolize the movie genre by color and the profitability of a movie by two overlaying circles. Furthermore, I implemented a hover interaction (showing details to the selected movie) and a click interaction (highlighting movies of the same genre).",
    "Acquired skills": ["d3.js", "JavaScript"],
    name: "scatterplot",
    link: "D3_Scatterplot/movies.html",
    timeframe: "Summer semester 2023",
  },
  {
    title: "Data Comic",
    "Short description": "Data Comic on the gender data gap. Created with two fellow students during an information visualization project.",
    "Long description": "During an information visualization project, I created this comic with two fellow students. I was responsible for all the drawings, as well as the research, storytelling and implementation of the part about <a href='projects/Data_Comic/Crashtest.html'>data gaps in crash testing</a>",
    "Acquired skills": ["git", "Data storytelling", "jQuery", "CSS"],
    name: "datacomic",
    link: "Data_Comic/Intro.html",
    timeframe: "Winter semester 2022/23",
  },

];
export default descriptions;
